from enum import StrEnum


class SourceType(StrEnum):
    TELEGRAM = "TELEGRAM"
    WEBSITE = "WEBSITE"
    MANUAL = "MANUAL"
    IMPORT = "IMPORT"
    ONE_C = "ONE_C"


class ProcessingStatus(StrEnum):
    NEW = "NEW"
    PARSED = "PARSED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class ProductCondition(StrEnum):
    NEW = "NEW"
    USED = "USED"
    REFURBISHED = "REFURBISHED"


class Availability(StrEnum):
    IN_STOCK = "IN_STOCK"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    UNKNOWN = "UNKNOWN"
    SUSPECT_MISSING = "SUSPECT_MISSING"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class ConflictStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"


class ParseStatus(StrEnum):
    PARSED = "PARSED"
    PARTIAL = "PARTIAL"
    REVIEW = "REVIEW"
    CONFLICT = "CONFLICT"
    IGNORED = "IGNORED"


class MatchStatus(StrEnum):
    EXACT_MATCH = "EXACT_MATCH"
    AUTO_CREATED = "AUTO_CREATED"
    REVIEW = "REVIEW"
    REJECTED = "REJECTED"
    CONFLICT_BLOCKED = "CONFLICT_BLOCKED"


class MatchStrategy(StrEnum):
    MODEL_CODE_EXACT = "MODEL_CODE_EXACT"
    ATTRIBUTES_EXACT = "ATTRIBUTES_EXACT"
    ALIAS_EXACT = "ALIAS_EXACT"
    UNIQUE_PRODUCT_PLUS_ATTRIBUTES = "UNIQUE_PRODUCT_PLUS_ATTRIBUTES"
    AUTO_CREATE_SAFE = "AUTO_CREATE_SAFE"
    AMBIGUOUS = "AMBIGUOUS"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    PARSER_CONFLICT = "PARSER_CONFLICT"


class SupplierSnapshotType(StrEnum):
    FULL = "FULL"
    PARTIAL = "PARTIAL"


class SupplierSnapshotStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"


class SupplierSnapshotItemStatus(StrEnum):
    SEEN = "SEEN"
    REVIEW = "REVIEW"
    CONFLICT = "CONFLICT"
    REJECTED = "REJECTED"


class TelegramCollectionMode(StrEnum):
    BACKFILL = "BACKFILL"
    INCREMENTAL = "INCREMENTAL"


class TelegramCollectionRunStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class TelegramMessageIngestionStatus(StrEnum):
    INGESTED = "INGESTED"
    DUPLICATE = "DUPLICATE"
    EDITED = "EDITED"
    IGNORED = "IGNORED"
    UNSUPPORTED_MEDIA_ONLY = "UNSUPPORTED_MEDIA_ONLY"


class SourceCollectionJobStatus(StrEnum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    RETRY_WAIT = "RETRY_WAIT"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class SourceCollectionJobType(StrEnum):
    SCHEDULED_INCREMENTAL = "SCHEDULED_INCREMENTAL"
    MANUAL_INCREMENTAL = "MANUAL_INCREMENTAL"
    MANUAL_BACKFILL = "MANUAL_BACKFILL"
    RETRY = "RETRY"


class OneCItemMatchStatus(StrEnum):
    MATCHED = "MATCHED"
    UNMATCHED = "UNMATCHED"
    AMBIGUOUS = "AMBIGUOUS"
    IGNORED = "IGNORED"


class OneCItemMatchStrategy(StrEnum):
    MANUAL = "MANUAL"
    INTERNAL_CODE = "INTERNAL_CODE"
    BARCODE_EXACT = "BARCODE_EXACT"
    SKU_EXACT = "SKU_EXACT"
    MODEL_CODE_EXACT = "MODEL_CODE_EXACT"
    NAME_EXACT = "NAME_EXACT"
    FUZZY_NAME = "FUZZY_NAME"


class OneCImportRunStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    REJECTED = "REJECTED"
    DUPLICATE = "DUPLICATE"


class OneCImportMode(StrEnum):
    FULL = "FULL"
    PARTIAL = "PARTIAL"


class PricingMode(StrEnum):
    BALANCED = "BALANCED"
    MARGIN = "MARGIN"
    AGGRESSIVE = "AGGRESSIVE"
    CLEARANCE = "CLEARANCE"
    MANUAL = "MANUAL"


class FulfillmentSource(StrEnum):
    OWN_STOCK = "OWN_STOCK"
    SUPPLIER = "SUPPLIER"
    NONE = "NONE"


class StockDecision(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSE = "PAUSE"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    REVIEW = "REVIEW"


class PriceRoundingMode(StrEnum):
    UP = "UP"
    NEAREST = "NEAREST"


class PricingReasonCode(StrEnum):
    OWN_STOCK_AVAILABLE = "OWN_STOCK_AVAILABLE"
    SUPPLIER_STOCK_AVAILABLE = "SUPPLIER_STOCK_AVAILABLE"
    NO_AVAILABLE_STOCK = "NO_AVAILABLE_STOCK"
    SUPPLIER_OFFER_STALE = "SUPPLIER_OFFER_STALE"
    SUPPLIER_CONFLICT = "SUPPLIER_CONFLICT"
    OWN_COST_MISSING = "OWN_COST_MISSING"
    SUPPLIER_COST_MISSING = "SUPPLIER_COST_MISSING"
    MANUAL_PRICE_BELOW_FLOOR = "MANUAL_PRICE_BELOW_FLOOR"
    INVALID_PRICING_POLICY = "INVALID_PRICING_POLICY"
    HARD_FLOOR_APPLIED = "HARD_FLOOR_APPLIED"
    MANUAL_PRICE_APPLIED = "MANUAL_PRICE_APPLIED"
    SUPPLIER_SELECTED_LOWEST_PRICE = "SUPPLIER_SELECTED_LOWEST_PRICE"


class ContentFactSource(StrEnum):
    PRODUCT = "PRODUCT"
    PRODUCT_VARIANT = "PRODUCT_VARIANT"
    PRODUCT_ALIAS = "PRODUCT_ALIAS"
    ONE_C = "ONE_C"
    SUPPLIER_OFFER = "SUPPLIER_OFFER"
    SUPPLIER_RAW = "SUPPLIER_RAW"
    MANUAL = "MANUAL"
    DERIVED_DETERMINISTIC = "DERIVED_DETERMINISTIC"


class ContentFactConfidence(StrEnum):
    CONFIRMED = "CONFIRMED"
    UNKNOWN = "UNKNOWN"
    CONFLICT = "CONFLICT"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ContentDraftStatus(StrEnum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    VALID = "VALID"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ContentValidationStatus(StrEnum):
    NOT_VALIDATED = "NOT_VALIDATED"
    VALID = "VALID"
    INVALID = "INVALID"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class ImageAssetSourceType(StrEnum):
    MANUAL_UPLOAD = "MANUAL_UPLOAD"
    SUPPLIER = "SUPPLIER"
    PRODUCT_LIBRARY = "PRODUCT_LIBRARY"
    GENERATED = "GENERATED"
    OTHER = "OTHER"


class ImageAssetStatus(StrEnum):
    READY = "READY"
    INVALID = "INVALID"
    DUPLICATE = "DUPLICATE"


class ImageSetStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"


class GenericCategory(StrEnum):
    SMARTPHONE = "SMARTPHONE"
    TABLET = "TABLET"
    SMART_WATCH = "SMART_WATCH"
    HEADPHONES = "HEADPHONES"
    LAPTOP = "LAPTOP"
    POWER_STATION = "POWER_STATION"
    GENERATOR = "GENERATOR"
    ACCESSORY = "ACCESSORY"
    OTHER = "OTHER"


class GenericListingStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_READY = "NOT_READY"
    APPROVED = "APPROVED"
    STALE = "STALE"
    REJECTED = "REJECTED"


class GenericReadinessStatus(StrEnum):
    NOT_READY = "NOT_READY"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    READY = "READY"
    APPROVED = "APPROVED"
    STALE = "STALE"


class MarketplaceReadinessStatus(StrEnum):
    DISABLED_CONTRACT_INCOMPLETE = "DISABLED_CONTRACT_INCOMPLETE"


class ListingReadinessReason(StrEnum):
    MISSING_CONTENT = "MISSING_CONTENT"
    CONTENT_INVALID = "CONTENT_INVALID"
    FACT_CONFLICT = "FACT_CONFLICT"
    FACTS_CHANGED = "FACTS_CHANGED"
    UNKNOWN_CONDITION = "UNKNOWN_CONDITION"
    UNKNOWN_REQUIRED_INTERNAL_FACT = "UNKNOWN_REQUIRED_INTERNAL_FACT"
    NO_IMAGES = "NO_IMAGES"
    IMAGE_INVALID = "IMAGE_INVALID"
    NO_PRICE = "NO_PRICE"
    PRICING_REVIEW = "PRICING_REVIEW"
    BELOW_HARD_FLOOR = "BELOW_HARD_FLOOR"
    NO_STOCK = "NO_STOCK"
    SUPPLIER_STALE = "SUPPLIER_STALE"
    SUPPLIER_CONFLICT = "SUPPLIER_CONFLICT"
    CONTENT_NOT_APPROVED = "CONTENT_NOT_APPROVED"
    IMAGES_NOT_APPROVED = "IMAGES_NOT_APPROVED"
    AVITO_CONTRACT_INCOMPLETE = "AVITO_CONTRACT_INCOMPLETE"
