from enum import StrEnum


class SourceType(StrEnum):
    TELEGRAM = "TELEGRAM"
    WEBSITE = "WEBSITE"
    MANUAL = "MANUAL"
    IMPORT = "IMPORT"


class ProcessingStatus(StrEnum):
    NEW = "NEW"
    PARSED = "PARSED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class ProductCondition(StrEnum):
    NEW = "NEW"
    USED = "USED"
    REFURBISHED = "REFURBISHED"


class Availability(StrEnum):
    IN_STOCK = "IN_STOCK"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    UNKNOWN = "UNKNOWN"
    SUSPECT_MISSING = "SUSPECT_MISSING"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class ConflictStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"


class ParseStatus(StrEnum):
    PARSED = "PARSED"
    PARTIAL = "PARTIAL"
    REVIEW = "REVIEW"
    CONFLICT = "CONFLICT"
    IGNORED = "IGNORED"


class MatchStatus(StrEnum):
    EXACT_MATCH = "EXACT_MATCH"
    AUTO_CREATED = "AUTO_CREATED"
    REVIEW = "REVIEW"
    REJECTED = "REJECTED"
    CONFLICT_BLOCKED = "CONFLICT_BLOCKED"


class MatchStrategy(StrEnum):
    MODEL_CODE_EXACT = "MODEL_CODE_EXACT"
    ATTRIBUTES_EXACT = "ATTRIBUTES_EXACT"
    ALIAS_EXACT = "ALIAS_EXACT"
    UNIQUE_PRODUCT_PLUS_ATTRIBUTES = "UNIQUE_PRODUCT_PLUS_ATTRIBUTES"
    AUTO_CREATE_SAFE = "AUTO_CREATE_SAFE"
    AMBIGUOUS = "AMBIGUOUS"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    PARSER_CONFLICT = "PARSER_CONFLICT"


class SupplierSnapshotType(StrEnum):
    FULL = "FULL"
    PARTIAL = "PARTIAL"


class SupplierSnapshotStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"


class SupplierSnapshotItemStatus(StrEnum):
    SEEN = "SEEN"
    REVIEW = "REVIEW"
    CONFLICT = "CONFLICT"
    REJECTED = "REJECTED"


class TelegramCollectionMode(StrEnum):
    BACKFILL = "BACKFILL"
    INCREMENTAL = "INCREMENTAL"


class TelegramCollectionRunStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class TelegramMessageIngestionStatus(StrEnum):
    INGESTED = "INGESTED"
    DUPLICATE = "DUPLICATE"
    EDITED = "EDITED"
    IGNORED = "IGNORED"
    UNSUPPORTED_MEDIA_ONLY = "UNSUPPORTED_MEDIA_ONLY"


class SourceCollectionJobStatus(StrEnum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    RETRY_WAIT = "RETRY_WAIT"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class SourceCollectionJobType(StrEnum):
    SCHEDULED_INCREMENTAL = "SCHEDULED_INCREMENTAL"
    MANUAL_INCREMENTAL = "MANUAL_INCREMENTAL"
    MANUAL_BACKFILL = "MANUAL_BACKFILL"
    RETRY = "RETRY"
